### ISSUE TITLE
Github repo

### ISSUE THREAD

**Issue by DarthGandalf** [JoeLametta/whipper#293]
Hi, if the development is now here, could you push update to https://github.com/Freso/morituri to mention that? I had to compare commit histories to find out which one is which.

**Comment by Freso** [comment]
I've deleted that repository now and forked https://github.com/JoeLametta/whipper to https://github.com/Freso/whipper instead.

That said, I don't know why you would think Freso/morituri would be the place development was happening. It was clearly marked as a fork of thomasvs/morituri and doesn't have any issues enabled for it (which is why I assume you filed your issue about it there). Note that the lead developers of `whipper` do not actually have write permission to forks of the project, so none of the main project people could have done anything about this, if I hadn't been around and was willing to do it.

All places that link to whipper (e.g., Linux distributions, MusicBrainz's wiki etc.) should be using this JoeLametta/whipper as the URL for the project, so if something somewhere links/linked to Freso/morituri, it would be great if you'd let us know so we can reach out and ask them to point to the actual upstream…

**Comment by DarthGandalf** [comment]
At first I discovered thomasvs/morituri, but that repo looked abandoned, so I looked at its [network graph](https://github.com/thomasvs/morituri/network) to check if there is an active fork. And yes, there was: Freso/morituri. Then I noticed that the name there is different, so googled for "whipper" and came here.
