### ISSUE TITLE
Please don't stop - despite the recent events (ANSWERED)

### ISSUE THREAD

**Issue by 45054** [JoeLametta/whipper#76]
Thanks

**Comment by ArchangeGabriel** [comment]
I second that. I will more than ever need a tool for ripping accurately my CD collection. Keep up the good work!

**Comment by MerlijnWajer** [comment]
I really only speak on my behalf, but I still want to merge back more work that I have done, and then start more work. There's work to be done past WCD and the project will also still be very useful.

**Comment by JoeLametta** [comment]
Thanks for the support.
I reassure you the project won't halt because of What.CD's shutdown.
Quoting from IRC:

RecursiveForest:
> I don't think we should stop work on whipper at all.
> Accurate CD ripping on linux is still important.
> But I don't think we should make the what.cd-enhanced EAC logger the default anymore. :)

Me:
> I won't stop working on "whipper" [...] in the near future

Now we'll need even more feedback here on GitHub (What.CD thread got wiped) in order to address issues and ideas regarding the project.

PS: As whipper seems the best name we came up with, I'm going to stick with it.

**Comment by BoBeR182** [comment]
+1 For whipper name and further development.
