### ISSUE TITLE
whipper not picking up all settings in whipper.conf

### ISSUE THREAD

**Issue by mokkurkalve** [JoeLametta/whipper#99]
This used to work a month or so ago.
I have my config in $HOME/.config/whipper/whipper.conf
which should be the same as $XDG_CONFIG_HOME/whipper/whipper.conf on my system anyway.
The config looks like:

[main]
path_filter_fat = True
path_filter_special = False

[drive:TSSTcorp%3ACDDVDW%20TS-U633J%20%3ATM00]
vendor = TSSTcorp
model = CDDVDW TS-U633J
release = TM00
read_offset = 6
defeats_cache = True

[rip.cd.rip]
unknown = True
output_directory = /home/eivind/rippers/whipper
track_template = %%r/%%A/%%d (%%y)/[%%t] %%n
disc_template = %%r/%%A/%%d (%%y)/%%A - %%d (%%y)
profile = flac

The settings under [main] and [drive:*] seems to be picked up as before but the settings under [rip.cd.rip] are not and those values fall back to default. This is happening with current git checkout as of today.

**Comment by ArchangeGabriel** [comment]
Most likely because the command is not rip.cd.rip anymore, but whipper.cd.rip (right?). Blind guess, but could you try replacing with that one (don’t have the time to look how the change was done right now).

**Comment by mokkurkalve** [comment]
Thanks but no difference. It still won't pick up those settings.

**Comment by ArchangeGabriel** [comment]
OK, so this will have to wait for someone being able to dig in the code to check when those settings are read and if something changed when the rip command was renamed.

**Comment by JoeLametta** [comment]
> Thanks but no difference. It still won't pick up those settings.

Didn't check throughly but have you tried changing `[rip.cd.rip]` to `[command.cd.rip]`?

**Comment by 45054** [comment]
You could also try to remove the spaces before and afther the "=" so it would look like:

output_directory=/home/eivind/rippers/whipper
track_template=%%r/%%A/%%d (%%y)/[%%t] %%n
disc_template=%%r/%%A/%%d (%%y)/%%A - %%d (%%y)

**Comment by mokkurkalve** [comment]
None of the proposed changes made any difference.

BTW. The command run are simply
whipper cd rip
And my OS are Arch Linux x86_64 current (as of today).

**Comment by diskotechjam** [comment]
Having a similar problem basically running the example config...
[rip.cd.rip]
unknown = True
output_directory = ~/Music
track_template = new/%%A/%%y - %%d/%%t - %%n
disc_template = %(track_template)s
profile = flac

The config file is  ~/.config/whipper/whipper.conf

**Comment by Freso** [comment]
`rip.cd.rip` definitely won't work anymore, so it doesn't make sense trying with that. Is there some documentation that says `rip.cd.rip` specifically?

**Comment by diskotechjam** [comment]
Yes. That's the way it's listed on the github homepage

https://github.com/JoeLametta/whipper#configuration-file-documentation

It's also not working with [command.cd.rip]

**Comment by peaveyman** [comment]
I can confirm this isn't working for me either. Here is my whipper.conf

[drive:TSSTcorp%3ACD/DVDW%20SH-S183L%3ASB01]
vendor = TSSTcorp
model = CD/DVDW SH-S183L
release = SB01
defeats_cache = True
read_offset = 6

[whipper.cd.rip]
track_template = %%A - %%d/%%d - %%t - %%n
disc_tramplate = %%A - %%d/%%A - %%d
output_directory = /home/gary/whipper
working_directory = /home/gary/whipper/

**Comment by ArchangeGabriel** [comment]
I’m trying to track this. If anyone wants to take a look, here is a good start: https://github.com/JoeLametta/whipper/commit/ace8d5ac22cc4638e9641dc3aa4a52178113c2c2#diff-a1778966d092b4c9aaf13b4e50fca475

**Comment by JoeLametta** [comment]
> I’m trying to track this. If anyone wants to take a look, here is a good start

I'm not sure but I think the regression was introduced with https://github.com/JoeLametta/whipper/commit/d1ed80d62af50b7ed5e6f690ad1012922a89a1ff.

**Comment by afcowie** [comment]
Just hit this as well. Anything we can to do help you diagnose?

**Comment by oliverhenshaw** [comment]
d1ed80d seems to regress config file parsing for me too. I see that this is a squash merge and tried to bisect through the individual commits from PR #92 but most of the commits would not run for me[1]. Perhaps someone with more familiarity with the code will have better luck - it is an easy bug to reproduce, after all.

[1]
e.g. the first commit, b9cf34bbca65e030cf6b15a5e7ac9fbbc9e2a0de "introduce logcommand.Lager, Whipper(); use argparse for whipper image commands, stub logging", installed locally via:
$ python2 ./setup.py install --home=~/tmp-scratch/tmp-rip/dist/
fails:
$ ./dist/bin/whipper cd rip
Traceback (most recent call last):
  File "./dist/bin/whipper", line 9, in <module>
    load_entry_point('whipper==0.4.0', 'console_scripts', 'whipper')()
  File "/home/oliver/tmp-scratch/tmp-rip/dist/lib/python/whipper-0.4.0-py2.7.egg/morituri/rip/main.py", line 27, in main
    ret = Whipper(sys.argv[1:], prog=os.path.basename(sys.argv[0]))
  File "/home/oliver/tmp-scratch/tmp-rip/dist/lib/python/whipper-0.4.0-py2.7.egg/morituri/rip/main.py", line 95, in __init__
    opt.remainder[1:], prog=prog + " " + opt.remainder[0]
  File "/home/oliver/tmp-scratch/tmp-rip/dist/lib/python/whipper-0.4.0-py2.7.egg/morituri/common/logcommand.py", line 50, in __init__
    command.Command.__init__(self, parentCommand, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'prog'

**Comment by MasterofJOKers** [comment]
As I see it, that functionality was removed with "https://github.com/JoeLametta/whipper/commit/d1ed80d62af50b7ed5e6f690ad1012922a89a1ff#diff-a1778966d092b4c9aaf13b4e50fca475L39" and I don't see it being added again. Especially, I don't see a way of the subcommand knowing its parent for building the dotted section name in the current implementation.

**Comment by Q3CPMA** [comment]
So are we supposed to use the command line arguments for now?

**Comment by xmixahlx** [comment]
I have a script i execute instead of whipper itself:
`
#!/bin/sh
## run whipper with config because config file in git is broken
whipper cd rip \
--prompt \
--offset 48 \
--unknown \
--cdr \
--output-directory=/mnt/Data/Media/Music/Ripped/ \
--disc-template="%A/%A - %d/%A - %d" \
--track-template="%A/%A - %d/%t - %a - %n";
exit
`

**Comment by smoneck** [comment]
But not every option is available using  command line arguments. Take `profile = flac`.
No idea how to set it to `wav`.

**Comment by JoeLametta** [comment]
> But not every option is available using command line arguments. Take profile = flac.
> No idea how to set it to wav.

That isn't supported anymore since whipper v0.5.0: now it's FLAC only (rationale in #130).
I'll document it [here](https://github.com/JoeLametta/whipper#backward-incompatible-changes).

**Comment by calumchisholm** [comment]
@MerlijnWajer - are you currently working on this, or would you mind if I picked it up?

I have some WIP code, but it would still need some more work before it's ready to merge. I don't want to spend time on it if you've already made good progress though.

**Comment by RecursiveForest** [comment]
By all means keep plugging away @calumchisholm -- I also have some unfinished code that works towards fixing this, but that shouldn't be a barrier towards actually fixing it if you can.

**Comment by calumchisholm** [comment]
I'll certainly keep looking at it when I get some time - it would be nice to get this functional again.

**Comment by calumchisholm** [comment]
While playing around in this area, I thought it might be a good idea to review the command-line arguments and config settings currently supported by whipper (or intended to be supported).

Most of these are quite well understood, and included only for the sake of completeness, however there are a few items (listed in the last section) that I would appreciate some input on though. Either their intended use is unclear, or I've identified them as possible targets for tidy-up, consolidation or moving elsewhere in the config hierarchy.

Feedback welcomed.


#### CLI Only
_Mainly single-use or debug options. Generally no value to writing them to whipper.conf_

* whipper --version
* whipper --help
* whipper.cd --toc-pickle
* whipper.cd --release-id
* whipper.image.retag --cuefile
* whipper.image.retag --release-id
* whipper.image.verify --cuefile
* whipper.offset.find --offsets
* whipper.debug.resultcache --logger
* whipper.debug.checksum --files
* whipper.debug.encode --input
* whipper.debug.encode --output
* whipper.debug.tag --file
* whipper.debug.musicbrainzngs --mbdiscid


#### whipper.conf only
_No (directly) corresponding command-line argument, but not an issue._

* [drive:] read_offset
  * Overridden by whipper.cd.rip --offset
* [drive:] defeats_cache
* [main] path_filter_fat
* [main] path_filter_special


#### CLI & whipper.conf
_Set either from CLI or whipper.conf. Well understood._

* whipper --eject
* whipper.cd.rip --offset
  * Overrides [drive:] read_offset
* whipper.cd.rip --output-directory
* whipper.cd.rip --working-directory
* whipper.cd.rip --track-template
* whipper.cd.rip --disc-template
* whipper.cd.rip --unknown
* whipper.cd.rip --cdr


#### Investigate 
_Possible candidates for tidy-up, or maybe just a lack of understanding on my part._

* whipper --record
  * Description reads "record API requests for playback", however it's really only the MusicBrainz release data which is saved. Presumably it's at the top-level because it can be used with either the `cd` or `image` commands, but it feels out of place (and a bit 'debuggy'). At the very least, the description text should better reflect its purpose.
* whipper.cd --prompt
* whipper.image.retag --prompt
  * Both of these commands support a `--prompt` argument. Is there value in keeping these separate, or could they be combined and promoted to the top-level?
* whipper.cd --country
* whipper.image.retag --country
  * Again - could these be combined?
* whipper.cd.rip --logger
  * Shouldn't this be a top-level argument and made available for commands other than 'rip'?
* whipper.cd.rip --force-overread
  * Should this be stored in the config file on a per-device setting (similar to `--offset`) or does it apply regardless of the drive used (as with `--cdr`)?

**Comment by RecursiveForest** [comment]
This PR fixes the config issue, so I wouldn't spend any more time on it: https://github.com/JoeLametta/whipper/pull/240

I have a proposal from some months ago in IRC for reworking the command line interface that I quite liked. If I remember when I get home I'll share it.
